INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(1,'¿Por qué desea adoptar un animal de compañía? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(2,'Si por algún motivo tuviera que cambiar de domicilio, ¿qué pasaría con su animal de compañía? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(3,'Con relación a la pregunta anterior ¿qué pasaría si los dueños de la nueva casa no aceptan animales de compañía? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(4,'¿Dónde dormirá la mascota adoptado? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(5,'¿Cuánto tiempo pasará sola la mascota adoptado? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(6,'¿Tienes otras mascotas en casa? ¿Qué pasará si no se llevan bien? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(7,'¿Todas las personas que viven en tu casa están de acuerdo con esta adopción? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(8,'¿Cómo es tu vivienda? ¿Es segura para una mascota? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(9,'¿Habrá quien lo saque a pasear y a hacer sus necesidades? *',true);
INSERT INTO pregunta (id_pregunta, pregunta, estado) VALUES(10,'¿Te comprometes a ponerle collar con una plaquita con nombre y teléfono, y sacarlo a pasear con correa y bolsitas para recoger sus heces? *',true);
